// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjQSYHhORzow5mLl36UHOPrwM30KFCjtI',
    appId: '1:227747847887:android:5e95fe9e3246cdb9c661ba',
    messagingSenderId: '227747847887',
    projectId: 'top5-d04a7',
    storageBucket: 'top5-d04a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCke5mOAUVSgNLOENg-9zlJYkn8Of5ssuU',
    appId: '1:227747847887:ios:8f5abe49dd4a4c8ac661ba',
    messagingSenderId: '227747847887',
    projectId: 'top5-d04a7',
    storageBucket: 'top5-d04a7.firebasestorage.app',
    androidClientId: '227747847887-o6864lomogk3ljrsnf1chnhvmt8kkt61.apps.googleusercontent.com',
    iosClientId: '227747847887-6hgmp6aerl9obfi2ql7m32ijnci272km.apps.googleusercontent.com',
    iosBundleId: 'com.topfive.top5',
  );

}